version: '1.0'
entity_id: 948cad33-870e-4d2d-bdeb-39ff4dd5a5f3
entity_type: organization
organization_id: 948cad33-870e-4d2d-bdeb-39ff4dd5a5f3
organization_name: parallelloop
context_type: settings
updated_at: '2026-01-12T14:33:38.377749'
data:
  name: Parallelloop AI
  slug: parallelloop
  description: ''
  created_at: '2026-01-12T06:59:45.253117+00:00'
processing_path: direct
